exporter.fhir.export = true
exporter.fhir.transaction_bundle = true
exporter.fhir.us_core_ig = true
exporter.baseDirectory = ./synthea_output
generate.only_alive_patients = true
generate.only_dead_patients = false
