services:
  hapi-fhir:
    image: hapiproject/hapi:v7.6.0
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /data/hapi/application.yaml
    volumes:
      - hapi-data:/data/hapi
    environment:
      HAPI_FHIR_FHIR_VERSION: R4
      HAPI_FHIR_SECURITY_ENABLED: "false"
      # JDBC settings to make HAPI persist FHIR resources into Postgres
      # For local testing these point at the same postgres service below.
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.lrigppqtqfztybxegils.supabase.co:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: CS6440healt
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

volumes:
  pgdata:

